import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'installation',
    'quickstart',
    {
      type: 'category',
      label: 'Physical AI Fundamentals',
      items: [
        'physical-ai/concepts',
        'simulation/digital-twins',
      ],
    },
    {
      type: 'category',
      label: 'Core Technologies',
      items: [
        'ros2/integration',
        'simulation/framework',
        'robotics/humanoid',
        'vla/systems',
      ],
    },
    {
      type: 'category',
      label: 'Curriculum Modules',
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          items: [
            'modules/module-1-ros2-nervous-system',
            'modules/module-1-ros2-nervous-system/chapter-1-introduction-to-ros2',
            'modules/module-1-ros2-nervous-system/chapter-2-nodes-and-topics',
            'modules/module-1-ros2-nervous-system/chapter-3-services-and-actions',
            'modules/module-1-ros2-nervous-system/chapter-4-ai-agent-integration',
          ],
        },
        {
          type: 'category',
          label: 'Module 2: Digital Twin Simulation',
          items: [
            'modules/module-2-digital-twin-simulation',
            'modules/module-2-digital-twin-simulation/chapter-1-introduction-to-digital-twins',
            'modules/module-2-digital-twin-simulation/chapter-2-gazebo-simulation-environment',
            'modules/module-2-digital-twin-simulation/chapter-3-unity-integration',
            'modules/module-2-digital-twin-simulation/chapter-4-sensor-simulation',
          ],
        },
        {
          type: 'category',
          label: 'Module 3: AI Robot Brain',
          items: [
            'modules/module-3-ai-robot-brain',
            'modules/module-3-ai-robot-brain/chapter-1-introduction-to-ai-robot-brains',
            'modules/module-3-ai-robot-brain/chapter-2-perception-systems',
            'modules/module-3-ai-robot-brain/chapter-3-planning-and-decision-making',
            'modules/module-3-ai-robot-brain/chapter-4-learning-and-adaptation',
          ],
        },
        {
          type: 'category',
          label: 'Module 4: VLA Integration',
          items: [
            'modules/module-4-vla-integration',
            'modules/module-4-vla-integration/chapter-1-introduction-to-vla-models',
            'modules/module-4-vla-integration/chapter-2-vla-implementation',
            'modules/module-4-vla-integration/chapter-3-vla-deployment-and-case-studies',
            'modules/module-4-vla-integration/chapter-4-future-trends-and-integration',
          ],
        },
        'weekly-breakdown',
        'assessments',
      ],
    },
    {
      type: 'category',
      label: 'Additional Specs',
      items: [{ type: 'autogenerated', dirName: 'specs' }],
    },
  ],
};

export default sidebars;
