import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    'installation',
    'quickstart',
    {
      type: 'category',
      label: 'Physical AI Fundamentals',
      items: [
        'physical-ai/concepts',
        'simulation/digital-twins',
      ],
    },
    {
      type: 'category',
      label: 'Core Technologies',
      items: [
        'ros2/integration',
        'simulation/framework',
        'robotics/humanoid',
        'vla/systems',
      ],
    },
    {
      type: 'category',
      label: 'Curriculum Modules',
      items: [
        'modules/module-1-ros2-nervous-system',
        'modules/module-2-digital-twin-simulation',
        'modules/module-3-ai-robot-brain',
        'modules/module-4-vla-integration',
        'weekly-breakdown',
        'assessments',
      ],
    },
    {
      type: 'category',
      label: 'Additional Specs',
      items: [{ type: 'autogenerated', dirName: 'specs' }],
    },
  ],
};

export default sidebars;
