openapi: 3.0.0
info:
  title: Physical AI Research Paper API
  description: API for managing the Physical AI & Humanoid Robotics research paper
  version: 1.0.0
  contact:
    name: Research Team
    email: research@physical-ai.org

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.physical-ai-research.org
    description: Production server

paths:
  /papers:
    get:
      summary: List all research papers
      description: Retrieve a list of all research papers with pagination
      parameters:
        - name: limit
          in: query
          description: Maximum number of papers to return
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 10
        - name: offset
          in: query
          description: Number of papers to skip
          required: false
          schema:
            type: integer
            minimum: 0
            default: 0
      responses:
        '200':
          description: List of papers
          content:
            application/json:
              schema:
                type: object
                properties:
                  papers:
                    type: array
                    items:
                      $ref: '#/components/schemas/Paper'
                  total:
                    type: integer
                  offset:
                    type: integer
                  limit:
                    type: integer
    post:
      summary: Create a new research paper
      description: Create a new research paper with initial metadata
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaperInput'
      responses:
        '201':
          description: Paper created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paper'
        '400':
          $ref: '#/components/responses/BadRequest'

  /papers/{paperId}:
    get:
      summary: Get a specific paper
      description: Retrieve details of a specific research paper
      parameters:
        - name: paperId
          in: path
          required: true
          description: Unique identifier of the paper
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Paper details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paper'
        '404':
          $ref: '#/components/responses/NotFound'
    put:
      summary: Update a paper
      description: Update the metadata and content of a research paper
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaperInput'
      responses:
        '200':
          description: Paper updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Paper'
        '404':
          $ref: '#/components/responses/NotFound'
    delete:
      summary: Delete a paper
      description: Delete a research paper and all associated content
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Paper deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'

  /papers/{paperId}/sections:
    get:
      summary: List paper sections
      description: Retrieve all sections of a specific paper
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of paper sections
          content:
            application/json:
              schema:
                type: object
                properties:
                  sections:
                    type: array
                    items:
                      $ref: '#/components/schemas/Section'
    post:
      summary: Create a new section
      description: Add a new section to a research paper
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SectionInput'
      responses:
        '201':
          description: Section created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Section'
        '404':
          $ref: '#/components/responses/NotFound'

  /papers/{paperId}/citations:
    get:
      summary: List paper citations
      description: Retrieve all citations in a specific paper
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of citations
          content:
            application/json:
              schema:
                type: object
                properties:
                  citations:
                    type: array
                    items:
                      $ref: '#/components/schemas/Citation'
    post:
      summary: Add a citation
      description: Add a new citation to a research paper
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CitationInput'
      responses:
        '201':
          description: Citation added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Citation'
        '400':
          $ref: '#/components/responses/BadRequest'

  /papers/{paperId}/validate:
    post:
      summary: Validate paper quality
      description: Run quality checks on a paper (citations, plagiarism, readability)
      parameters:
        - name: paperId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Validation results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationResult'

components:
  schemas:
    Paper:
      type: object
      required:
        - id
        - title
        - word_count
        - status
        - created_date
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 500
        abstract:
          type: string
          maxLength: 5000
        word_count:
          type: integer
          minimum: 5000
          maximum: 7000
        status:
          type: string
          enum: [draft, review, approved, published]
        created_date:
          type: string
          format: date-time
        last_modified:
          type: string
          format: date-time
        authors:
          type: array
          items:
            $ref: '#/components/schemas/Author'
        readability_score:
          type: number
          minimum: 10.0
          maximum: 12.0
        peer_reviewed_percentage:
          type: number
          minimum: 50.0
          maximum: 100.0

    PaperInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 500
        abstract:
          type: string
          maxLength: 5000

    Section:
      type: object
      required:
        - id
        - title
        - content
        - section_type
        - order
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        content:
          type: string
        section_type:
          type: string
          enum: [overview, foundation, analysis, synthesis, appendix]
        order:
          type: integer
        readability_score:
          type: number
          minimum: 10.0
          maximum: 12.0

    SectionInput:
      type: object
      required:
        - title
        - content
        - section_type
        - order
      properties:
        title:
          type: string
          maxLength: 200
        content:
          type: string
        section_type:
          type: string
          enum: [overview, foundation, analysis, synthesis, appendix]
        order:
          type: integer

    Citation:
      type: object
      required:
        - id
        - source_type
        - title
        - is_peer_reviewed
        - citation_text
      properties:
        id:
          type: string
          format: uuid
        source_type:
          type: string
          enum: [journal, conference, preprint, whitepaper, technical_report]
        title:
          type: string
          maxLength: 1000
        authors:
          type: array
          items:
            type: string
        publication_date:
          type: string
          format: date
        doi:
          type: string
        url:
          type: string
          format: uri
        is_peer_reviewed:
          type: boolean
        citation_text:
          type: string
        retrieved_date:
          type: string
          format: date

    CitationInput:
      type: object
      required:
        - source_type
        - title
        - citation_text
      properties:
        source_type:
          type: string
          enum: [journal, conference, preprint, whitepaper, technical_report]
        title:
          type: string
          maxLength: 1000
        authors:
          type: array
          items:
            type: string
        publication_date:
          type: string
          format: date
        doi:
          type: string
        url:
          type: string
          format: uri
        is_peer_reviewed:
          type: boolean
        citation_text:
          type: string

    Author:
      type: object
      required:
        - id
        - first_name
        - last_name
        - institution
      properties:
        id:
          type: string
          format: uuid
        first_name:
          type: string
          maxLength: 100
        last_name:
          type: string
          maxLength: 100
        institution:
          type: string
          maxLength: 200
        email:
          type: string
          format: email
        orcid:
          type: string

    ValidationResult:
      type: object
      properties:
        citations_valid:
          type: boolean
        plagiarism_check_passed:
          type: boolean
        readability_score:
          type: number
          minimum: 10.0
          maximum: 12.0
        peer_reviewed_percentage:
          type: number
          minimum: 50.0
          maximum: 100.0
        overall_status:
          type: string
          enum: [pass, fail, warning]

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string

  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'